# Generated by Django 4.1.5 on 2023-01-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.CharField(max_length=255)),
                ('theme_name', models.CharField(max_length=255)),
                ('icons', models.CharField(max_length=255)),
                ('premium', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=255)),
                ('icons', models.CharField(max_length=255)),
                ('wallpaper', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_theme', models.CharField(max_length=255)),
                ('premium', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=255)),
                ('icons', models.CharField(max_length=255)),
                ('wallpaper', models.CharField(max_length=255)),
                ('widgets', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_themes', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Wallpapers', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('wallpaper', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Widgets', models.CharField(max_length=255)),
                ('premium', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=255)),
                ('widgets', models.CharField(max_length=255)),
            ],
        ),
    ]
